export const GET_VENDOR_LIST = 'GET_VENDOR_LIST';
export const GET_VENDOR_LIST_SUCCESS = 'GET_VENDOR_LIST_SUCCESS';
export const GET_VENDOR_LIST_ERROR = 'GET_VENDOR_LIST_ERROR';

export const SAVE_VENDOR = 'SAVE_VENDOR';
export const SAVE_VENDOR_SUCCESS = 'SAVE_VENDOR_SUCCESS';
export const SAVE_VENDOR_ERROR = 'SAVE_VENDOR_ERROR';

export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';
